import { readdirSync, readFileSync, writeFileSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const componentsDir = resolve(root, 'src/components')
const outputPath = resolve(root, 'src/index.ts')

function discoverComponents() {
  if (!existsSync(componentsDir)) return []
  return readdirSync(componentsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => {
      const dirName = d.name
      const indexPath = resolve(componentsDir, dirName, 'index.ts')
      const vuePath = resolve(componentsDir, dirName, `N${dirName}.vue`)
      if (!existsSync(indexPath) && !existsSync(vuePath)) return null

      const componentName = `N${dirName}`

      let exportNames = [componentName]
      if (existsSync(indexPath)) {
        const content = readFileSync(indexPath, 'utf-8')
        const match = content.match(/export\s*\{([^}]+)\}/)
        if (match) {
          exportNames = match[1]
            .split(',')
            .map((s) => s.trim())
            .filter(Boolean)
        }
      }

      return {
        dirName,
        componentName,
        importPath: `./components/${dirName}`,
        exportNames,
      }
    })
    .filter(Boolean)
    .sort((a, b) => a.dirName.localeCompare(b.dirName))
}

function generate(components) {
  const importLines = components
    .map((c) => {
      const names = c.exportNames.join(', ')
      return `import { ${names} } from "${c.importPath}";`
    })
    .join('\n')

  const exportLines = components
    .map((c) => `  ${c.exportNames.join(',\n  ')},`)
    .join('\n')

  const componentMap = components
    .map((c) => `  ${c.componentName},`)
    .join('\n')

  return `import type { App, Component } from "vue";

// Components — auto-generated by scripts/gen-index.mjs
${importLines}

export {
${exportLines}
};

// Types
export * from "./types";

// Styles — base reset/variables first, then UnoCSS utilities
import "./styles/index.css";
import "virtual:uno.css";

// Plugin — auto-registers all discovered components
const components: Record<string, Component> = {
${componentMap}
};

export default {
  install(app: App) {
    Object.entries(components).forEach(([name, component]) => {
      app.component(name, component);
    });
  },
};
`
}

const components = discoverComponents()
const content = generate(components)
writeFileSync(outputPath, content, 'utf-8')
console.log(`[gen-index] Generated src/index.ts with ${components.length} components:`)
components.forEach((c) => console.log(`  - ${c.componentName} (${c.dirName})`))
