// 根据 src/components/<Name>/index.ts 自动生成统一入口 src/index.ts。
// 新增组件时只需新建组件目录并在其 index.ts 中具名导出组件，无需修改任何配置文件。
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const componentsDir = path.join(root, "src", "components");
const entryFile = path.join(root, "src", "index.ts");

const HEADER = `// @generated by scripts/generate-entry.mjs — 请勿手动修改。
// 新增组件：创建 src/components/<Name>/index.ts 并具名导出组件，然后运行任意 npm 脚本即可自动登记。`;

function readNamedExports(file) {
  const source = readFileSync(file, "utf8");
  const names = [];
  for (const match of source.matchAll(/export\s*\{([^}]+)\}/g)) {
    for (const part of match[1].split(",")) {
      const name = part.trim().split(/\s+as\s+/).pop().trim();
      if (name && name !== "default" && !/^type\s/.test(part.trim())) {
        names.push(name);
      }
    }
  }
  return names;
}

const entries = [];
for (const dir of readdirSync(componentsDir, { withFileTypes: true })) {
  if (!dir.isDirectory()) continue;
  const indexFile = path.join(componentsDir, dir.name, "index.ts");
  try {
    const names = readNamedExports(indexFile);
    if (names.length > 0) {
      entries.push({ dir: dir.name, names });
    } else {
      console.warn(`[gen] 跳过 ${dir.name}：index.ts 中没有具名导出`);
    }
  } catch {
    console.warn(`[gen] 跳过 ${dir.name}：缺少 index.ts`);
  }
}

entries.sort((a, b) => a.dir.localeCompare(b.dir));

if (entries.length === 0) {
  console.error("[gen] 未在 src/components 下发现任何组件");
  process.exit(1);
}

const allNames = entries.flatMap((e) => e.names);
const imports = entries
  .map((e) => `import { ${e.names.join(", ")} } from "./components/${e.dir}";`)
  .join("\n");
const exports = `export {\n  ${allNames.join(",\n  ")},\n};`;
const registry = `const components: Record<string, Component> = {\n  ${allNames.join(",\n  ")},\n};`;

const content = `${HEADER}
import type { App, Component } from "vue";

${imports}

${exports}

// Types
export * from "./types";

// Styles（变量 + 重置 + 编译后的原子类，打包进 dist/es/style.css）
import "./styles/index.css";
import "virtual:uno.css";

${registry}

export default {
  install(app: App) {
    Object.entries(components).forEach(([name, component]) => {
      app.component(name, component);
    });
  },
};
`;

let previous = "";
try {
  previous = readFileSync(entryFile, "utf8");
} catch {
  // 文件不存在，直接写入
}
if (previous === content) {
  console.log(`[gen] src/index.ts 已是最新（${entries.length} 个组件）`);
  process.exit(0);
}

writeFileSync(entryFile, content);
console.log(`[gen] 已生成 src/index.ts，登记 ${entries.length} 个组件：${allNames.join(", ")}`);
