// @generated by scripts/generate-entry.mjs — 请勿手动修改。
// 新增组件：创建 src/components/<Name>/index.ts 并具名导出组件，然后运行任意 npm 脚本即可自动登记。
import type { App, Component } from "vue";

import { NAvatar } from "./components/Avatar";
import { NBadge } from "./components/Badge";
import { NBreadcrumb } from "./components/Breadcrumb";
import { NButton } from "./components/Button";
import { NCard } from "./components/Card";
import { NInput } from "./components/Input";
import { NModal } from "./components/Modal";
import { NSkeleton } from "./components/Skeleton";
import { NTable } from "./components/Table";
import { NTabs } from "./components/Tabs";
import { NToast } from "./components/Toast";

export {
  NAvatar,
  NBadge,
  NBreadcrumb,
  NButton,
  NCard,
  NInput,
  NModal,
  NSkeleton,
  NTable,
  NTabs,
  NToast,
};

// Types
export * from "./types";

// Styles（变量 + 重置 + 编译后的原子类，打包进 dist/es/style.css）
import "./styles/index.css";
import "virtual:uno.css";

const components: Record<string, Component> = {
  NAvatar,
  NBadge,
  NBreadcrumb,
  NButton,
  NCard,
  NInput,
  NModal,
  NSkeleton,
  NTable,
  NTabs,
  NToast,
};

export default {
  install(app: App) {
    Object.entries(components).forEach(([name, component]) => {
      app.component(name, component);
    });
  },
};
