import type { App, Component } from "vue";

// Components — auto-generated by scripts/gen-index.mjs
import { NAvatar } from "./components/Avatar";
import { NBadge } from "./components/Badge";
import { NBreadcrumb } from "./components/Breadcrumb";
import { NButton } from "./components/Button";
import { NCard } from "./components/Card";
import { NInput } from "./components/Input";
import { NModal } from "./components/Modal";
import { NSkeleton } from "./components/Skeleton";
import { NTable } from "./components/Table";
import { NTabs } from "./components/Tabs";
import { NToast } from "./components/Toast";

export {
  NAvatar,
  NBadge,
  NBreadcrumb,
  NButton,
  NCard,
  NInput,
  NModal,
  NSkeleton,
  NTable,
  NTabs,
  NToast,
};

// Types
export * from "./types";

// Styles — base reset/variables first, then UnoCSS utilities
import "./styles/index.css";
import "virtual:uno.css";

// Plugin — auto-registers all discovered components
const components: Record<string, Component> = {
  NAvatar,
  NBadge,
  NBreadcrumb,
  NButton,
  NCard,
  NInput,
  NModal,
  NSkeleton,
  NTable,
  NTabs,
  NToast,
};

export default {
  install(app: App) {
    Object.entries(components).forEach(([name, component]) => {
      app.component(name, component);
    });
  },
};
